spring:
  application:
    name: social
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/note
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081